# 批量创建容器，适合开发一个项目时用，多个项目同时开发，容器还是要追求一下共用性
# 所以多项目开发时，建议每个服务单独创建容器

# 以下 volumes 配置 都是以 . 当前目录，为单一项目服务创建的容器
# 以下方式创建的容器，其它项目不方便直接使用

version: "3"
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - .:/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: nirvana72/php-env:7.4-fpm-alpine
    volumes:
      - .:/www
      # - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
      # - ./docker/php/ext:/usr/local/lib/php/extensions/no-debug-non-zts-20190902
  mysql:
    image: mysql:5.7.29
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456